appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Lsm1npV5NBVo6vKMUoBbHbpQ3CXoDnc5KcGd82PpetLaqoG9x65RsvIO3S34qsMnMZUer6hswfRnmcraOQlEM41vAcjXRfLgzj9qgEp6389U6l5reG4orDFCua524lrYnnbKaxi6v6QsyY/zsqXtsF2XmZ3prEczbEVOU0mgOeyXORS4sKqcCG7oDJJL8/BLmt88Z+kEYtHBb45Vf9qwR+wzlTb0ELSbTJjf17cMeMOgNiilacPKlk5Ckd/W9V9uwyS+QnivO3WDjVpSSEU8iggQdQv/+BwgUj3jpSY2tuJ3tIvQqFLu3mvRDuRM0e6RNcdb4Tjgy2qqLSk6UayJ/839q/3PPWKuK/6tEUMugrk0ARDJJ2LRtDAEmidDpjiAElOzUcqgq9qYIZX8Hbd73ftfdxCBdFiYflVBDIFEzdM6ZXJQQsQhTF0z82XbVZDmgBvnlD1SVJqzjYgFo6GItRNQ+KueoQ+sGYevy+9v00Jpf/Ao00z/oVnKACbIbuTIhevVKQvNcOCyynSZhiPan514OolXF+qpTyHqt+6dbF9MqnxXcoOUu9d9GYU0adMHwSgvX6b8I+DkHiJfJAGFkyHXOHEnek2jRA9DTnN1n42IIINUkMuqAdh9F0AAUQv5QKjUYpmH1fe1Dk5b8ZrqCU1elSETI6uAOKOIk4Yq2qM=}
